### ISSUE TITLE
Add Shifts - CRUD 

### ISSUE THREAD

**Issue by maxdobeck** [maxdobeck/zeiter#27]
All shifts should be globally visible.  Users should be able to Create, Read, Edit, and Destroy Shifts.

A shift has:
- Name of Shift: String
- Start_time of Shift: DateTime
- End_time of Shift: DateTime
- Duration of Shift: Int
- Repeat of Shift: Bool - Does the shift repeat?
- Repeat_num of Shift: Int range:[0 to 52] - How many times does this shift repeat (in weeks)
- Repeat_end of repeat: DateTime

**Comment by kapoorlakshya** [comment]
I'll start with the model creation first and then consult you on the overall workflow.

I think we should also have a flag "swappable" to allow/disallow shift exchange. Or is that unnecessary? Can't decide.

**Comment by maxdobeck** [comment]
That is necessary. It's easier to control it at the shift level than an
individual user level.

**Comment by kapoorlakshya** [comment]
Added attributes `swappable`, `shift_id` unique to the schedule, and `clone_of`.

The idea with the `clone_of` is that when a shift is marked as repeated, we can clone the original shift object N times where N is the number of times this shift is repeated. `clone_of` will just hold the ID of the original shift. This will make plotting calendar entries easier since all we have to do is iterate through a list of shift objects and display them on the calendar. 

Even though this will work, I think there is a more sophisticated way to do this. Do you have any ideas?

**Comment by maxdobeck** [comment]
1. Is `shift_id`the uuid of a shift?  For `clone_of` I think it's sort of a repeat of the repeat_num attribute. I was thinking we'll just reference that and process each day 1 at a time. 

Otherwise we'll end up duplicating quite a bit if shift data in the db. I would recommend making an event in google calendar. Watch their ui panel to see what info they collect. 

2. Join table is the only way to go I think. ☹️ The model will get kind of complex and we're going to have to sit down and think this one out.

**Comment by kapoorlakshya** [comment]
Closing this because we are now able to CRUD shifts.
